### PR TITLE
Fix for issue svthalia#26, added setting up development to the README… 

### PR DESCRIPTION
**Pull request by Gulianrdgd**
….md and fixed poetry lock by updating xmlsec

### CODE REVIEW

**Comment by JobDoesburg** [comment]
Nice! Some suggestions I noticed right now:

- With a filter for room A, it is still possible to drag in a reservation for room B (that will first appear and then disappear again, because it is for a different room. It would be better UX to just be able to drag in a reservation to the room you're currently viewing
- Maybe it is possible to put the filter in bootstrap tabs? https://getbootstrap.com/docs/5.1/components/navs-tabs/#tabs

**Comment by EDMDanceCoin** [comment]
How it would have worked is that you could make the reservation form another room but it would only disappear if you applied the filter again. How I have added some line of code which disables the dragging if the filter is not on that room.

UI is also now in bootstrap style and scales nicely on mobile

**Comment by Gulianrdgd** [comment]
How it would have worked is that you could make the reservation for another room but it would only disappear if you applied the filter again. Now I have added some lines of code which disables the dragging if the filter is not on that room.

UI is also now in bootstrap style and scales nicely on mobile

**Comment by JobDoesburg** [comment]
> Now I have added some lines of code which disables the dragging if the filter is not on that room.

Nice

> UI is also now in bootstrap style and scales nicely on mobile

Not necessarily what I thought of, but sure. This is a bit of a problem though (not sure if this is only safari)

image

**Comment by Gulianrdgd** [comment]
https://getbootstrap.com/docs/4.3/components/input-group/#custom-select

I'm pretty sure this is how its supposed to look in bootstrap 4.3

**Review by JobDoesburg — APPROVED** [review]

**Pull request merged**
